### ISSUE TITLE
torch OOM error on windows but works fine on WSL2

### ISSUE THREAD

**Issue by onlyinheaven** [kijai/ComfyUI-DepthAnythingV2#20]
I run DAV2 with ComfyUI on WSL2, and it works fine. However, when I run DAV2 using the same image and model on Windows with ComfyUI_windows_portable, I encounter a torch.OutOfMemoryError. I’m wondering why this happens. Could it be because the Windows version of ComfyUI doesn’t have xformers installed? The image resolution is 2316x3088, and the model is ViT-L FP32. The log and environtments are as follows.
# Env on windows:
### Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\applications\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\applications\ComfyUI_windows_portable\ComfyUI
** Log path: E:\applications\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   1.3 seconds: E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130761 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\applications\ComfyUI_windows_portable\ComfyUI\web
E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Total VRAM 24564 MB, total RAM 130761 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
xFormers not available
xFormers not available

Depthcrafter Nodes Loaded

### ComfyUI Revision: 2776 [83ca8911] | Released on '2024-10-20'
# Error log:
   Traceback (most recent call last):
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\nodes.py", line 160, in process
    depth = model(img.unsqueeze(0).to(device))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dpt.py", line 191, in forward
    features = self.pretrained.get_intermediate_layers(x, self.intermediate_layer_idx[self.encoder], return_class_token=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2.py", line 277, in _get_intermediate_layers_not_chunked
    x = blk(x)
        ^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2_layers\block.py", line 247, in forward
    return super().forward(x_or_x_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2_layers\block.py", line 105, in forward
    x = x + attn_residual_func(x)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2_layers\block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2_layers\attention.py", line 70, in forward
    return super().forward(x)
           ^^^^^^^^^^^^^^^^^^
  File "E:\applications\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthAnythingV2\depth_anything_v2\dinov2_layers\attention.py", line 55, in forward
    attn = q @ k.transpose(-2, -1)
           ~~^~~~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.

# Env on WSL:
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-21 14:55:23.294803
** Platform: Linux
** Python version: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)
[GCC 13.3.0]
** Python executable: /home/liuyangchenxu/miniforge3/envs/comfyui/bin/python
** ComfyUI Path: /home/liuyangchenxu/workrepo/ComfyUI
** Log path: /home/liuyangchenxu/workrepo/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /home/liuyangchenxu/workrepo/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.4 seconds: /home/liuyangchenxu/workrepo/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24564 MB, total RAM 48174 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /home/liuyangchenxu/workrepo/ComfyUI/web
/home/liuyangchenxu/miniforge3/envs/comfyui/lib/python3.9/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Depthcrafter Nodes Loaded

### ComfyUI Revision: 2766 [7390ff3b] | Released on '2024-10-16'
Total VRAM 24564 MB, total RAM 48174 MB
pytorch version: 2.4.1+cu121
xformers version: 0.0.28.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync

**Comment by kijai** [comment]
Yes it's because of xformers, I've been meaning to look into it to see if it's possible to not require that.

**Comment by kijai** [comment]
Ok in the end it wasn't too complicated, should work better now without xformers.

**Comment by onlyinheaven** [comment]
> Ok in the end it wasn't too complicated, should work better now without xformers.

Great! After updating the code, it runs smoothly on Windows now. Thanks！
